version: '3'
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./unknwon-react-diary/:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    tty: true
