service: comconfirm-lambda

provider:
  name: aws
  runtime: go1.x
  region: ap-northeast-1
  profile: amagai

package:
  exclude:
    - ./**
  include:
    - ./bin/**

functions:
  testlambda:
    handler: bin/comconfirm-lambda
    name: test-communication-confirm-lambda
    events:
      # API Gateway にて起動
      - http:
          path: /test/get
          method: get
    headers:
      - Content-Type
      - X-Amz-Date
      - Authorization
      - X-Api-Key
      - X-Amz-Security-Token
