Resources:
  diaryStoreDynamoDBTable:
    Type: AWS::DynamoDB::Table
    DeletionPolicy: Retain
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: post_at
          AttributeType: N
        - AttributeName: status_post_at
          AttributeType: S
        - AttributeName: author
          AttributeType: S
        - AttributeName: receiver
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: post_at
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: receiver-status_post_at-index
          KeySchema:
            - AttributeName: receiver
              KeyType: HASH
            - AttributeName: status_post_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
        - IndexName: author-status_post_at-index
          KeySchema:
            - AttributeName: author
              KeyType: HASH
            - AttributeName: status_post_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      TableName: ${self:custom.diaryStoreDynamoDBTable}
